source: app
destination: app/_site

# Site settings
title: Piotr Zawadzki
subtitle: Senior Android Developer
description: > # this means to ignore newlines until "baseurl:"
  Piotr Zawadzki's profile page.
author: Piotr Zawadzki
author_website: https://zawadz88.github.io
email: zawadz88@gmail.com

#baseurl: "/jekyll-polymer"  # Subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
                            # Currently `gulp serve:dist` does not work with a baseurl specified. For this purpose,
                            # temporarily comment out this parameter
url: "https://zawadz88.github.io"  # Base hostname & protocol for your site

github_username:  zawadz88
linkedin_username: piotr-zawadzki-66343833
stackoverflow_user_id: 973379

# Gems
gems:

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
